---
  - name: Install go
    command:
      argv:
        - bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
        - gvm install go1.4 -B
        - gvm use go1.4
        - export GOROOT_BOOTSTRAP=$GOROOT
        - gvm install go1.19
        - gvm use go1.19 --default

