---
  - name: Clean gvm files
    file:
      path: ~/.gvm
      state: absent

  - name: Install gvm
    shell: |
      /bin/bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
    args:
      executable: /bin/bash

  - name: Install go
    shell: |
      source ~/.gvm/scripts/gvm
      gvm install go1.19 -B
      gvm use go1.19 --default
    args:
      executable: /bin/bash
