---
  - name: Install libfuse2 (requirements to run AppImage)
    become: yes
    apt:
      name: libfuse2

  - name: Download nvim 
    get_url:
      url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
      dest: /tmp/nvim

  - name: Install nvim
    become: yes
    ansible.builtin.copy:
      remote_src: yes
      src: /tmp/nvim
      dest: /usr/bin/nvim
      mode: '0755'

  - name: Install vim-plug
    shell: |
      sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

  - name: Install python nvim module
    pip:
      name: pynvim

