---
  - name: Set source of nodejs
    become: yes
    become_user: root
    shell: |
     curl -fsSL https://deb.nodesource.com/setup_18.x | bash - 

  - name: Install nodejs
    apt:
      name: nodejs
      update_cache: yes
