---
  - name: Install rg
    become: true
    apt:
      name: ripgrep
      update_cache: yes

  - name: Install fzf
    shell: |
      git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
      yes | ~/.fzf/install

  - name: Install lazygit, lf
    shell: |
      source ~/.gvm/scripts/gvm
      go install github.com/jesseduffield/lazygit@latest
      env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest
    args:
      executable: /bin/bash

  - name: Install z.lua
    git:
      repo: https://github.com/skywind3000/z.lua.git
      dest: ~/github/z.lua

  - name: Install tmuxp
    become: true
    apt:
      name: tmuxp
      update_cache: yes
