---
  - name: Clear tmux compiling related files
    shell: |
      rm -rf /tmp/tmux*

  - name: Compile and install tmux
    shell: |
      cd /tmp
      wget https://github.com/tmux/tmux/releases/download/3.3a/tmux-3.3a.tar.gz
      tar -zxf tmux-*.tar.gz
      cd tmux-*/
      ./configure
      make && make install
      apt remove tmux
      mv ./tmux /usr/bin/tmux

  - name: Download oh my tmux
    git:
      repo: https://github.com/gpakosz/.tmux.git
      dest: ~/github/tmux

  - name: Link oh my tmux setting
    file:
      src: ~/github/tmux/.tmux.conf
      dest: ~/.tmux.conf
      state: hard

