- name: Test connection
  hosts: all
  tasks:
    - name: Ping
      ping:
    - name: Show whoami
      command: whoami
      register: whoami
    - debug: var=whoami.stdout 

- name: Initialize directory for github repos
  hosts: all
  tasks:
    - name: Create ~/github
      file:
        path: "~/github"
        state: directory

- name: Installing
  hosts: all
  become: yes
  roles:
    - nvim
    - zsh
    - tools
    - tmux
    - node
    - settings
